import type { ResearchProvider, ResearchLeadInput, ResearchBrief } from "./types";

export class MockResearchProvider implements ResearchProvider {
  readonly name = "mock";

  async research(lead: ResearchLeadInput): Promise<ResearchBrief> {
    return {
      summary:
        `${lead.firstName} ${lead.lastName} is a ${lead.title ?? "professional"}` +
        (lead.company ? ` at ${lead.company}` : "") +
        ". (Stub — configure PERPLEXITY_API_KEY for live research.)",
      relevance:     "Stub: relevance will be populated once Perplexity is configured.",
      signals:       "Stub: public signals will appear here.",
      outreachAngle: "Stub: outreach angle will be generated by the research provider.",
      sources:       [],
    };
  }
}
